# Generated by Django 3.1.1 on 2020-09-17 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(max_length=999)),
                ('price', models.PositiveIntegerField()),
                ('sale_start', models.DateTimeField(blank=True)),
                ('sale_end', models.DateTimeField(blank=True)),
            ],
        ),
    ]
