# Generated by Django 3.1.1 on 2020-09-17 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_auto_20200917_2206'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='sale_end',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='sale_start',
            field=models.DateTimeField(null=True),
        ),
    ]
