# Generated by Django 3.1.1 on 2020-09-17 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_auto_20200917_2207'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='sale_end',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='sale_start',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
